# Generated by Django 5.2.14 on 2026-05-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField()),
                ('tech_stack', models.CharField(help_text='Comma separated, e.g. Python, ROS2, C++', max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('video_embed', models.TextField(blank=True, help_text='Paste YouTube embed iframe here', null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order, lower numbers first')),
            ],
            options={
                'ordering': ['order', '-date_completed'],
            },
        ),
    ]
